### 게시글 다수 조회
GET {{server_url}}/boards?word=내용&page=0&size=5
User-Agent: {{user_agent}}


### 게시글 조회
GET {{server_url}}/boards/5
User-Agent: {{user_agent}}


### 게시글 등록
POST {{server_url}}/boards
User-Agent: {{user_agent}}
Content-Type: application/json

{
  "title": "제목",
  "content": "내용"
}


### 게시글 수정
PATCH {{server_url}}/boards/3
User-Agent: {{user_agent}}
Content-Type: application/json

{
  "title": "제목3",
  "content": "내용3"
}


### 게시글 삭제
DELETE {{server_url}}/boards/4
User-Agent: {{user_agent}}


### 게시글 조회수 히트
POST {{server_url}}/boards/1/hit
User-Agent: {{user_agent}}


### 게시글 좋아요/싫어요
PUT {{server_url}}/boards/4/like-or-hate
User-Agent: {{user_agent}}
Content-Type: application/json

{
  "likeOrHate": "NONE"
}