### 이메일 중복 체크
GET {{server_url}}/users/email/duplicate?email=hkhong91@gmail.com


### 이름 중복 체크
GET {{server_url}}/users/name/duplicate?name=홍아지


### 회원 로그인
POST {{server_url}}/users/signin
Content-Type: application/json

{
  "email": "hkhong91@gmail.com",
  "password": "1234"
}


### 회원 가입
POST {{server_url}}/users/signup
Content-Type: application/json

{
  "email": "hkhong91@gmail.com",
  "name": "홍아지",
  "password": "1234",
  "gender": "MALE"
}