### 이메일 중복 체크
GET {{server_url}}/users/emails/hkhong91@gmail.com/duplicate


### 이름 중복 체크
GET {{server_url}}/users/names/홍아지/duplicate


### 회원 로그인
POST {{server_url}}/users/signin
Content-Type: application/json

{
  "email": "hkhong91@gmail.com",
  "password": "1234"
}


### 회원 가입
POST {{server_url}}/users/signup
Content-Type: application/json

{
  "email": "hkhong91@gmail.com",
  "name": "홍아지",
  "password": "1234",
  "gender": "MALE"
}

### 이메일 변경
PATCH {{server_url}}/users/1/email
Content-Type: application/json

{
  "email": "hkhong91@gmail.com"
}

### 이름 변경
PATCH {{server_url}}/users/1/name
Content-Type: application/json

{
  "name": "홍아지"
}

### 패스워드 변경
PATCH {{server_url}}/users/1/password
Content-Type: application/json

{
  "password": "1234"
}